---
- name: Configuración inicial para el cluster de raspberry
  hosts: all
  become: true

  # Usuario y contraseña por defecto de Raspbian
  vars:
    ansible_user: pi
    ansible_ssh_pass: raspberry

  # Prompt interactivo para crear el nuevo usuario y su contraseña
  vars_prompt:
    - name: ansible_user
      prompt: Usuario raspberry
      private: no
      default: pi

    - name: ansible_ssh_pass
      prompt: "contraseña usuario raspberry"
      default: raspberry

    - name: new_user
      prompt: New username
      private: no

    - name: new_user_password
      prompt: password
      private: yes
      encrypt: sha512_crypt
      confirm: yes

    - name: user_pub_key
      prompt: Ruta de la llave pública del Usuario
      private: no
      default: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"


  tasks:
    # Actualizamos el sistema
    - name: Actualizar sistema
      apt:
        name: "*"
        state: latest
        update_cache: yes

    # Crear usuario
    - name: Crear usuario "{{ new_user }}"
      ansible.builtin.user:
        name: "{{ new_user }}"
        comment: Username create with Ansible
        password: "{{ new_user_password }}"

    # Añadir usuario al grupo sudo
    - name: Añadir nuevo usuario a SUDO
      ansible.builtin.user:
        name: "{{ new_user }}"
        groups: sudo
        append: yes

    # Habilitar el uso de SUDO sin pedir contraseña
    - name: Deshabilitar la petición de contraseña para comandos con SUDO
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/010_{{ new_user }}-nopasswd"
        line: "{{ new_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes

    # Copiar llave SSH
    - name: Copiar llave pública a máquina remota
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', user_pub_key) }}"

    # Cambiar hostname
    - name: Cambiar hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    # Configurar NTP
    - name: Configurar el NTP para usar los servidores de PTB time
      ansible.builtin.lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^#NTP='
        line: NTP=ptbtime1.ptb.de ptbtime2.ptb.de ptbtime3.ptb.de
    - name: Configurar zona horaria a Europe/Madrid
      community.general.timezone:
        name: Europe/Madrid

    # Configurar /etc/hosts, asigna el nombre local
    - name: Cambiar archivo /etc/hosts
      template:
        src: templates/basic_hosts.j2
        dest: /etc/hosts
        backup: yes

    # Deshabilitar el acceso root por SSH
    - name: Deshabilitar el acceso al usuario root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: PermitRootLogin No
      notify:
      - Restart SSH

    # Deshabilitar el acceso por contraseña
    - name: Deshabilitar el acceso por contraseña
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: PasswordAuthentication no
      notify:
      - Restart SSH

    # Borrar usuario PI
    - name: Borrar usuario "pi"
      become_user: "{{ new_user }}"
      ansible.builtin.user:
        name: pi
        state: absent
        remove: yes
        force: yes


  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
